[core]
temp_tracks_directory="temp_tracks"

[interfaces.web-ui]
port = 3000

[interfaces.subsonic-api]
port = 8000

[[modules.storage]]
id="main_disk"
name="Main Disk"
tag="LOC"
enabled=true
priority=10
params= { save_directory="Z:/music_library" }

[modules.search.MBZ]
enabled = false
priority = 1

[modules.search.ITS]
priority = 1
enabled = true

[modules.downloader.SLS]
enabled = true
priority = 1
params = { api_route="http://127.0.0.1:5030", download_path="Z:/", username="slskd", password="slskd", share_tracks=false }

